#!/usr/bin/env node

var connect = require('connect');
var serveStatic = require('serve-static');

var port = 8080;
var dirname = './';
var ssl = false;

process.argv.forEach(function (val, index, array) {
    if (val.match(/port/)){
        port = val.replace(/port=/, '');
    } else if (val.match(/dirname/)) {
        dirname = val.replace(/dirname=/, '');
    } else if (val.match(/ssl/)) {
        ssl = val.replace(/ssl=/, '');
    }
});

connect().use(serveStatic(dirname)).listen(port, function(){
	console.log('Serving ' + dirname  +' on '+ port  +'...');
});
